/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spc_mp3convert_NativesMethods */

#ifndef _Included_com_spc_mp3convert_NativesMethods
#define _Included_com_spc_mp3convert_NativesMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spc_mp3convert_NativesMethods
 * Method:    read
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_spc_mp3convert_NativesMethods_read
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_spc_mp3convert_NativesMethods
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spc_mp3convert_NativesMethods_getLameVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
